serviceTree:
  landscape: &landscape raichu
  cluster: &cluster onyx

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

kyverno:
  backgroundController:
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  admissionController:
    replicas: 3
    container:
      resources:
        limits:
          memory: 512Mi
          cpu: 500m
        requests:
          cpu: 125m
          memory: 128Mi
    podLabels:
      <<: *tags
    podAnnotations:
      <<: *tags
  cleanupController:
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  reportsController:
    podLabels:
      <<: *tags
    podAnnotations:
      <<: *tags

# -- Kyverno Policy Reporter Configuration. See [Policy Reporter](https://github.com/kyverno/policy-reporter)
policy-reporter:
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  podLabels:
    <<: *tags
  podAnnotations:
    <<: *tags
  ui:
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    podLabels:
      <<: *tags
    podAnnotations:
      <<: *tags
