version: '3'

env:
  RELEASE_NAME: sulfoxide-argon

includes:
  util: tasks/Taskfile.util.yaml
  pichu:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pichu
      CLUSTER: opal
  entei:topaz:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: entei
      CLUSTER: topaz

tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update

  latest:
    desc: Get the latest version of Kyverno as Policy Engine
    cmds:
      - task: util:latest
        vars:
          REPO_NAME: kyverno
          REPO_URL: https://kyverno.github.io/kyverno/
          CHART_NAME: kyverno
      - task: util:latest
        vars:
          REPO_NAME: policy-reporter
          REPO_URL: https://kyverno.github.io/policy-reporter
          CHART_NAME: policy-reporter
